server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://mysql-192be37d-vietlinh1482004-83dd.g.aivencloud.com:10404/quanh
    driverClassName: com.mysql.cj.jdbc.Driver
    username: avnadmin
    password: AVNS_lMHHQZnQlVaKNWFxbgP
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB



jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

mailServer:
  host: smtp.gmail.com
  port: 587
  email: forgot.pass.bid@gmail.com
  password: xsiq grfy wyil myzp
  protocol: smtp
  isSSL: false

app:
  client-url: http://localhost:5173
  verification-token-expiry: 24 # hours
  reset-token-expiry: 1 # hours for password reset

vietmap:
  api:
    key: ec4b6f6a60186d81c08db7c3beeed4abafcd2fc367c9f746
    base-url: https://maps.vietmap.vn/api

aws:
  s3:
    access-key-id: tsymgkl7
    secret-access-key: zzl9t8bd6n6jwn88
    bucket-name: tsymgkl7-travel
    region: ap-southeast-1
    endpoint: http://objectstorageapi.ap-southeast-1.clawcloudrun.com
